id: P007071
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5312
  title: དགའ་ལྡན་ཕུན་ཚོགས་གླིང་གི་བྱུང་བ།
  author: ''
  volumes:
    fb76f57ee1d44774ab16cb331ea25868:
      image_group_id: I3CN5314
      title: ''
      volume_number: 1
      total_pages: 442
ebook_metadata:
  title: དགའ་ལྡན་ཕུན་ཚོགས་གླིང་གི་བྱུང་བ།
  author: ''
  sku: P007071
  cover: cover.jpg
  layers:
  - pagination
