id: P007071
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5312
  title: དགའ་ལྡན་ཕུན་ཚོགས་གླིང་གི་བྱུང་བ།
  author: ''
  volumes:
    fb76f57ee1d44774ab16cb331ea25868:
      image_group_id: I3CN5314
      title: ''
      volume_number: 1
      total_pages: 442
